language: python

python:
  - "3.7.5"

services:
  - postgresql

before_script:
  - psql -c "CREATE USER clem WITH PASSWORD 'clem';" -U postgres
  - psql -c "CREATE DATABASE empath_e;" -U postgres
  - psql -c "GRANT ALL ON DATABASE empath_e TO clem;" -U postgres
  - psql -c "ALTER USER clem WITH CREATEDB;" -U postgres

install:
  - pip install -r requirements.txt

script:
  - python manage.py collectstatic
  - python manage.py test
