language: python

python:
  - "3.7.5"

services:
  - postgresql

before_script:
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
  - psql -c "CREATE DATABASE test_empath_e;" -U postgres
  - psql -c "GRANT ALL ON DATABASE test_empath_e TO test;" -U postgres
  - cp config/database.yml.travis config/database.yml

install:
  - pip install -r requirements.txt

script:
  - python manage.py collectstatic
  - python manage.py test
